[package]
name = "blackscholes_python"
version = "0.9.0"
edition = "2021"
license = "MIT"
description = "Black-Scholes option pricing model calculator"
repository = "https://github.com/hayden4r4/blackscholes-rust"

[dependencies]
statrs = "0.16.0"
pyo3 = { version = "0.17.3", features = ["extension-module"] }

[lib]
crate-type = ["cdylib"]
name = "blackscholes_python"
