[package]
name = "blackscholes_python"
version = "0.10.7"
edition = "2021"
license = "MIT"
description = "Black-Scholes option pricing model calculator"
repository = "https://github.com/hayden4r4/blackscholes-rust/tree/python_package"
documentation = "https://docs.rs/blackscholes_python"
readme = "README.md"
authors = ["Hayden Rose"]
keywords = ["finance", "option", "python", "blackscholes", "option-pricing"]

[dependencies]
statrs = "0.16.0"
pyo3 = { version = "0.17.3", features = ["extension-module"] }

[lib]
crate-type = ["cdylib"]
name = "blackscholes_python"
